### ISSUE TITLE
Need overflow-y to be an option

### ISSUE THREAD

**Issue by mfor** [bertrandg/angular-split#107]
When I disable overflow-y: auto; in the inspector, all my troubles go away.  I have been trying to remove them myself using .style.overflowY = 'pleaseStop', but they keep getting set.  

Have I missed something obvious again, or where can I remove overflow-y from angular-split?

**Comment by alexisdoualle** [comment]
I made it work with 
```css
split-area{
	overflow-y: hidden !important;
}
```
