### ISSUE TITLE
Not able to roll or unroll the area horizontally on gutterClick

### ISSUE THREAD

**Issue by kirandas82** [bertrandg/angular-split#143]
Not able to do roll or unroll the area horizontally on gutterClick. Is there any way?

**Comment by bertrandg** [comment]
Did you tried this?
https://bertrandg.github.io/angular-split/#/examples/gutter-click-roll-unroll

**Comment by kirandas82** [comment]
yes> I tried, this will work perfectly for vertical roll but if I change to horizontal view, it is not working

**Comment by bertrandg** [comment]
You hadn't specified a height, this is why it wasn't working, I just add:

```css
.split-example {
  width: 500px;
  height: 500px;
  background: yellow;
}
```

And it works:
https://stackblitz.com/edit/angular-asnzzm?file=src%2Fapp%2Fapp.component.css
