### ISSUE TITLE
styling split-gutter

### ISSUE THREAD

**Issue by kejtizuki** [bertrandg/angular-split#24]
Hey, 
I'm trying to delete the background image from split-gutter tag and style it my own way. I'm trying to do that this way, but it's not working: 
split-gutter {
    background-image: none !important;
}
Could you please help me?

**Comment by bertrandg** [comment]
Hi @kejtizuki 

You can do it like that:

``` css
split-gutter {
  background-image: url('') !important;
}
```

Or if you want to override with another image, check this example:
https://plnkr.co/edit/gSmnlv?p=preview
