### ISSUE TITLE
split-area with iframe - drag gutter issue

### ISSUE THREAD

**Issue by dhasi** [bertrandg/angular-split#31]
I have two split-areas, one of them containing a iframe. If I try to make the first split-area bigger, by dragging the gutter over the iframe, the gutter stucks until I leave the iframe-area again.

https://plnkr.co/edit/XQMNILs3NfLKXnh3TMCy?p=preview

**Comment by bertrandg** [comment]
Hi @dhasi ,
Thanks to reporting, i've experiment what you describe.

Sadly, I don't see any easy fix to solve this, it comes from the `mousemove` event listener on `document` which is not triggered when mouse over the `iframe`:
https://github.com/bertrandg/angular-split/blob/master/src/split.component.ts#L274

But i've write a hack to bypass the behavior. The idea is to cover `split-area` with transparent div when dragging gutters to keep `mousemove` on `document` firing.

Here it is: http://plnkr.co/edit/VSQPQ6?p=preview

```html
<split direction="horizontal" (dragStart)="showIframeHider = true" (dragEnd)="showIframeHider = false">
  <split-area [size]="30">
      <p>Lorem ipsum dolor sit amet...</p>
  </split-area>
  <split-area [size]="70">
      <div>
        <iframe src="https://bertrandg.github.io/angular-split" frameborder="0" width="100%" height="100%"></iframe>
        <div [hidden]="showIframeHider === false" class="hack-iframe-hider"></div>
      </div>
  </split-area>
</split>
```

```css
split-area > div {
  position: relative;
  height: 100%;
  overflow: hidden;
}

.hack-iframe-hider {
  background: rgba(0, 0, 0, .2);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
