### ISSUE TITLE
how to hide the gutter?

### ISSUE THREAD

**Issue by bokire** [bertrandg/angular-split#99]
if set size=0 in the split ,could remove the gutter

**Comment by leonardochaia** [comment]
There's a ``visible`` property on the ``split-area``.
```html
<split-area [visible]="false"></split-area>
```

Please close this if you've solved it.

**Comment by bokire** [comment]
@leonardochaia sorry,i want to hide the gutter, not the area

**Comment by leonardochaia** [comment]
Sorry, I misread you.

**Comment by m0uneer** [comment]
**A workaround:**

Add the following style to your component

```css
.hide-split-gutter {
  ::ng-deep split-gutter {
    display: none !important;
  }
}
```

And use it as the following:

```html
<split [ngClass]="{'hide-split-gutter': isSplitGutterHidden}">
```
